### ISSUE TITLE
用这个出现：SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by babafeng** [messense/teambition-api#5]
```Python
tb = Teambition(client_key, client_secret)

# 获取授权地址
url = tb.oauth.get_authorize_url(redirect_uri)
print(url)

access_token = tb.oauth.fetch_access_token(code)
```
然后出现：
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

**Comment by messense** [comment]
`pip install requests[security]` 再试下。

**Comment by messense** [comment]
另：http://docs.python-requests.org/en/master/user/advanced/#ca-certificates

**Comment by babafeng** [comment]
谢谢，但是还有一个问题，函数：`fetch_access_token(“授权码”)`中的授权码是怎么获得的呢
```Python
access_token = tb.oauth.fetch_access_token(code)
```

**Comment by babafeng** [comment]
我是通过访问：
```Python
```

**Comment by babafeng** [comment]
我是通过访问下面生成的url，跳转的回调地址中的code=xxxxx，然后使用这个code出现401，错误
```Pyhton
url = tb.oauth.get_authorize_url(redirect_uri)
print(url)
```

**Comment by messense** [comment]
exception 内容怎么说。

**Comment by messense** [comment]
https://docs.teambition.com/wiki/errors

**Comment by babafeng** [comment]
错误是：106  invalid grant，我是用浏览器访问获取到的authorize_url，然后手动复制的这个code，、

**Comment by messense** [comment]
确认你复制对了。

**Comment by babafeng** [comment]
终于搞明白了，非常感谢
